# Generated by Django 2.1.4 on 2018-12-20 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('des', models.TextField(blank=True, verbose_name='about disease')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='patient Name')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=12)),
                ('mobileNo', models.CharField(max_length=10, verbose_name='mobile Number')),
                ('address', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patientimg', models.ImageField(blank=True, null=True, upload_to='patientimg', verbose_name='patient photo')),
                ('bloodgroup', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('ab', 'AB')], max_length=12)),
                ('other', models.TextField(blank=True, verbose_name='other problems')),
                ('diseases', models.ManyToManyField(blank=True, to='patientreport.Disease')),
            ],
            options={
                'verbose_name_plural': 'Patient Details',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PatientMeetingRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingrecord', to='patientreport.PatientDetails')),
            ],
            options={
                'verbose_name_plural': 'Patient Meeting Records',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PatientTestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportimg', models.ImageField(upload_to='patientreports/')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TestReport', to='patientreport.PatientDetails')),
            ],
            options={
                'verbose_name_plural': 'Patient Test Reports',
                'ordering': ('timestamp',),
            },
        ),
    ]
