# Generated by Django 2.1.4 on 2018-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='des',
            field=models.TextField(blank=True, verbose_name='About Disease'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('ab', 'AB')], max_length=12, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='mobileNo',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other Problems'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='patientimg',
            field=models.ImageField(blank=True, null=True, upload_to='patientimg', verbose_name='Patient photo'),
        ),
        migrations.AlterField(
            model_name='patienttestreport',
            name='reportimg',
            field=models.ImageField(blank=True, null=True, upload_to='patientreports/', verbose_name='Report Image'),
        ),
    ]
